/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check with DB and Redis latency */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus metrics scrape endpoint */
        get: operations["getPrometheusMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and receive a JWT */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session token */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the currently authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change the current user's password */
        patch: operations["changePassword"];
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users (ADMIN only) */
        get: operations["listUsers"];
        put?: never;
        /** Create a new user (ADMIN only) */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a user's role (ADMIN only) */
        patch: operations["updateUserRole"];
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a user (ADMIN only) */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/revoke-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke all active sessions for a user (ADMIN only) */
        post: operations["revokeUserSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated research metrics */
        get: operations["getMetricsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/status-breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Grant counts grouped by status */
        get: operations["getStatusBreakdown"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monthly submissions and awards over time */
        get: operations["getMetricsTimeseries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/awards-by-sponsor-type": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Awarded amount grouped by sponsor type */
        get: operations["getAwardsBySponsorType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rich analytics dashboard payload */
        get: operations["getInsights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List grants with filtering and pagination */
        get: operations["listGrants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grants/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export filtered grants as CSV (or JSON with ?format=json) */
        get: operations["exportGrants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grants/expiring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Grants grouped into expiry buckets (0-30/31-60/61-90 days) */
        get: operations["getExpiringGrants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single grant with its sponsor/PI/department */
        get: operations["getGrantById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grants/{id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Semantically similar grants (vector search; empty when embeddings disabled) */
        get: operations["getSimilarGrants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/faculty/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Faculty ranked by total awarded amount */
        get: operations["getFacultyLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all departments */
        get: operations["listDepartments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sponsors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all sponsors */
        get: operations["listSponsors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask a natural-language question (RAG, streamed as SSE) */
        post: operations["askQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest grants from CSV (async; returns a job acknowledgement) */
        post: operations["ingestGrants"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the status of an ingestion job (ADMIN only) */
        get: operations["getIngestJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dry-run reconciliation of a CSV against DB state (ADMIN only) */
        post: operations["reconcileGrants"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Grant lifecycle status
         * @enum {string}
         */
        GrantStatus: "DRAFT" | "SUBMITTED" | "UNDER_REVIEW" | "AWARDED" | "DECLINED" | "WITHDRAWN";
        /**
         * @description Type of funding sponsor
         * @enum {string}
         */
        SponsorType: "FEDERAL" | "STATE" | "FOUNDATION" | "INDUSTRY" | "INTERNAL" | "OTHER";
        /** @description A research grant record */
        Grant: {
            id: number;
            title: string;
            sponsorId: number;
            piId: number;
            departmentId: number;
            amount: number;
            /** @enum {string} */
            status: "DRAFT" | "SUBMITTED" | "UNDER_REVIEW" | "AWARDED" | "DECLINED" | "WITHDRAWN";
            submittedAt: string | null;
            awardedAt: string | null;
            endAt?: string | null;
            createdAt: string;
            updatedAt: string;
        };
        /** @description A faculty member (PI) */
        Faculty: {
            id: number;
            name: string;
            /** Format: email */
            email: string;
            departmentId: number;
        };
        /** @description University department */
        Department: {
            id: number;
            name: string;
        };
        /** @description Grant sponsor organization */
        Sponsor: {
            id: number;
            name: string;
            /** @enum {string} */
            sponsorType: "FEDERAL" | "STATE" | "FOUNDATION" | "INDUSTRY" | "INTERNAL" | "OTHER";
        };
        /** @description A grant with resolved sponsor/PI/department */
        GrantWithRelations: {
            id: number;
            title: string;
            sponsorId: number;
            piId: number;
            departmentId: number;
            amount: number;
            /** @enum {string} */
            status: "DRAFT" | "SUBMITTED" | "UNDER_REVIEW" | "AWARDED" | "DECLINED" | "WITHDRAWN";
            /** Format: date-time */
            submittedAt: string | null;
            /** Format: date-time */
            awardedAt: string | null;
            /** Format: date-time */
            endAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            sponsor?: {
                id: number;
                name: string;
                /** @enum {string} */
                sponsorType: "FEDERAL" | "STATE" | "FOUNDATION" | "INDUSTRY" | "INTERNAL" | "OTHER";
            };
            pi?: {
                id: number;
                name: string;
                /** Format: email */
                email: string;
                departmentId: number;
            };
            department?: {
                id: number;
                name: string;
            };
        };
        /** @description Standard API error envelope */
        ErrorResponse: {
            error: {
                message: string;
                code: string;
                statusCode: number;
                timestamp: string;
                fields?: {
                    [key: string]: string[];
                };
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy or degraded (Redis down) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok" | "degraded" | "unhealthy";
                        timestamp: string;
                        service: string;
                        checks: {
                            database: {
                                /** @enum {string} */
                                status: "ok" | "error";
                                latencyMs: number;
                            };
                            redis: {
                                /** @enum {string} */
                                status: "ok" | "error";
                                latencyMs: number;
                            };
                        };
                    };
                };
            };
            /** @description Service is unhealthy (database unreachable) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPrometheusMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus text format metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken: string;
                        expiresIn: string;
                        user: {
                            id: number;
                            /** Format: email */
                            email: string;
                            name: string;
                            /** @enum {string} */
                            role: "ADMIN" | "VIEWER";
                        };
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: {
                            userId: number;
                            /** Format: email */
                            email: string;
                            role: string;
                        };
                    };
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    currentPassword: string;
                    newPassword: string;
                };
            };
        };
        responses: {
            /** @description Password changed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated user list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            id: number;
                            /** Format: email */
                            email: string;
                            name: string;
                            /** @enum {string} */
                            role: "ADMIN" | "VIEWER";
                            /** Format: date-time */
                            createdAt: string;
                        }[];
                        total: number;
                        page: number;
                        pageSize: number;
                        totalPages: number;
                    };
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden — insufficient role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    name: string;
                    password: string;
                    /** @enum {string} */
                    role: "ADMIN" | "VIEWER";
                };
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        /** Format: email */
                        email: string;
                        name: string;
                        /** @enum {string} */
                        role: "ADMIN" | "VIEWER";
                        /** Format: date-time */
                        createdAt: string;
                    };
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden — insufficient role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateUserRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    role: "ADMIN" | "VIEWER";
                };
            };
        };
        responses: {
            /** @description User with updated role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        /** Format: email */
                        email: string;
                        name: string;
                        /** @enum {string} */
                        role: "ADMIN" | "VIEWER";
                    };
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden — insufficient role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden — insufficient role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    revokeUserSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden — insufficient role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMetricsSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Summary KPIs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        totalSubmissions: number;
                        totalAwardedAmount: number;
                        awardRate: number;
                        medianTimeToAward: number | null;
                    };
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getStatusBreakdown: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status breakdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "DRAFT" | "SUBMITTED" | "UNDER_REVIEW" | "AWARDED" | "DECLINED" | "WITHDRAWN";
                        count: number;
                    }[];
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMetricsTimeseries: {
        parameters: {
            query?: {
                months?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timeseries data array */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        month: string;
                        submissions: number;
                        awards: number;
                        awardedAmount: number;
                    }[];
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAwardsBySponsorType: {
        parameters: {
            query?: {
                months?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sponsor type breakdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sponsorType: string;
                        awardedAmount: number;
                        count: number;
                    }[];
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getInsights: {
        parameters: {
            query?: {
                months?: number;
                departmentId?: number;
                sponsorType?: string;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Insights dashboard data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        summary: {
                            submissions: number;
                            awards: number;
                            awardRate: number;
                            totalAwardedAmount: number;
                            medianTimeToAward: number | null;
                            avgAwardSize: number;
                        };
                        timeseries: {
                            month: string;
                            submissions: number;
                            awards: number;
                            awardedAmount: number;
                            statusCounts: {
                                [key: string]: number;
                            };
                        }[];
                        dailyActivity: {
                            date: string;
                            submissions: number;
                            awards: number;
                            awardedAmount: number;
                        }[];
                        sponsorBreakdown: {
                            name: string;
                            sponsorType: string | null;
                            awardedAmount: number;
                            count: number;
                        }[];
                        departmentBreakdown: {
                            departmentId: number;
                            name: string;
                            awardedAmount: number;
                            awards: number;
                            submissions: number;
                        }[];
                        funnel: {
                            submitted: number;
                            underReview: number;
                            awarded: number;
                            declined: number;
                        };
                    };
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listGrants: {
        parameters: {
            query?: {
                department?: number;
                sponsor?: number;
                status?: "DRAFT" | "SUBMITTED" | "UNDER_REVIEW" | "AWARDED" | "DECLINED" | "WITHDRAWN";
                date_from?: string | null;
                date_to?: string | null;
                search?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated grant list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            id: number;
                            title: string;
                            sponsorId: number;
                            piId: number;
                            departmentId: number;
                            amount: number;
                            /** @enum {string} */
                            status: "DRAFT" | "SUBMITTED" | "UNDER_REVIEW" | "AWARDED" | "DECLINED" | "WITHDRAWN";
                            /** Format: date-time */
                            submittedAt: string | null;
                            /** Format: date-time */
                            awardedAt: string | null;
                            /** Format: date-time */
                            endAt?: string | null;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        }[];
                        total: number;
                        page: number;
                        pageSize: number;
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    exportGrants: {
        parameters: {
            query?: {
                department?: number;
                sponsor?: number;
                status?: "DRAFT" | "SUBMITTED" | "UNDER_REVIEW" | "AWARDED" | "DECLINED" | "WITHDRAWN";
                date_from?: string | null;
                date_to?: string | null;
                search?: string;
                format?: "csv" | "json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exported grants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                    "application/json": {
                        id: number;
                        title: string;
                        status: string;
                        amount: number;
                        pi: {
                            name: string;
                            email: string;
                        };
                        department: string;
                        sponsor: {
                            name: string;
                            type: string;
                        };
                        submittedAt: string | null;
                        awardedAt: string | null;
                    }[];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getExpiringGrants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Expiring grants by bucket */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        buckets: {
                            /** @enum {string} */
                            label: "0-30" | "31-60" | "61-90";
                            daysFrom: number;
                            daysTo: number;
                            count: number;
                            totalAmount: number;
                            grants: {
                                id: number;
                                title: string;
                                sponsorId: number;
                                piId: number;
                                departmentId: number;
                                amount: number;
                                /** @enum {string} */
                                status: "DRAFT" | "SUBMITTED" | "UNDER_REVIEW" | "AWARDED" | "DECLINED" | "WITHDRAWN";
                                /** Format: date-time */
                                submittedAt: string | null;
                                /** Format: date-time */
                                awardedAt: string | null;
                                /** Format: date-time */
                                endAt?: string | null;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                                sponsor?: {
                                    id: number;
                                    name: string;
                                    /** @enum {string} */
                                    sponsorType: "FEDERAL" | "STATE" | "FOUNDATION" | "INDUSTRY" | "INTERNAL" | "OTHER";
                                };
                                pi?: {
                                    id: number;
                                    name: string;
                                    /** Format: email */
                                    email: string;
                                    departmentId: number;
                                };
                                department?: {
                                    id: number;
                                    name: string;
                                };
                                daysUntilExpiry: number;
                                grantNumber?: string | null;
                            }[];
                        }[];
                        totalCount: number;
                        totalAmount: number;
                    };
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getGrantById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grant detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        title: string;
                        sponsorId: number;
                        piId: number;
                        departmentId: number;
                        amount: number;
                        /** @enum {string} */
                        status: "DRAFT" | "SUBMITTED" | "UNDER_REVIEW" | "AWARDED" | "DECLINED" | "WITHDRAWN";
                        /** Format: date-time */
                        submittedAt: string | null;
                        /** Format: date-time */
                        awardedAt: string | null;
                        /** Format: date-time */
                        endAt?: string | null;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                        sponsor?: {
                            id: number;
                            name: string;
                            /** @enum {string} */
                            sponsorType: "FEDERAL" | "STATE" | "FOUNDATION" | "INDUSTRY" | "INTERNAL" | "OTHER";
                        };
                        pi?: {
                            id: number;
                            name: string;
                            /** Format: email */
                            email: string;
                            departmentId: number;
                        };
                        department?: {
                            id: number;
                            name: string;
                        };
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSimilarGrants: {
        parameters: {
            query?: {
                k?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Similar grants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            id: number;
                            title: string;
                            sponsorId: number;
                            piId: number;
                            departmentId: number;
                            amount: number;
                            /** @enum {string} */
                            status: "DRAFT" | "SUBMITTED" | "UNDER_REVIEW" | "AWARDED" | "DECLINED" | "WITHDRAWN";
                            /** Format: date-time */
                            submittedAt: string | null;
                            /** Format: date-time */
                            awardedAt: string | null;
                            /** Format: date-time */
                            endAt?: string | null;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                            sponsor?: {
                                id: number;
                                name: string;
                                /** @enum {string} */
                                sponsorType: "FEDERAL" | "STATE" | "FOUNDATION" | "INDUSTRY" | "INTERNAL" | "OTHER";
                            };
                            pi?: {
                                id: number;
                                name: string;
                                /** Format: email */
                                email: string;
                                departmentId: number;
                            };
                            department?: {
                                id: number;
                                name: string;
                            };
                            score: number;
                        }[];
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getFacultyLeaderboard: {
        parameters: {
            query?: {
                department?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked faculty list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        facultyId: number;
                        facultyName: string;
                        departmentName: string;
                        totalAwarded: number;
                        rank: number;
                    }[];
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listDepartments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Departments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        name: string;
                    }[];
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listSponsors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sponsors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        name: string;
                        /** @enum {string} */
                        sponsorType: "FEDERAL" | "STATE" | "FOUNDATION" | "INDUSTRY" | "INTERNAL" | "OTHER";
                    }[];
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    askQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    question: string;
                };
            };
        };
        responses: {
            /** @description Server-sent event stream (event: text | sources | done) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ingestGrants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "text/plain": string;
            };
        };
        responses: {
            /** @description Ingestion accepted (async job) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        jobId: string;
                        /** @enum {string} */
                        status: "queued" | "completed";
                        totalRows: number;
                        batches: number;
                        errors: {
                            row: number;
                            error: string;
                        }[];
                    };
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden — insufficient role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getIngestJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingestion job status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        jobId: string;
                        /** @enum {string} */
                        status: "queued" | "processing" | "completed";
                        totalRows: number;
                        totalBatches: number;
                        batchesDone: number;
                        inserted: number;
                        updated: number;
                        errors: {
                            row: number;
                            error: string;
                        }[];
                        createdAt: string;
                        updatedAt: string;
                    };
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden — insufficient role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reconcileGrants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "text/plain": string;
            };
        };
        responses: {
            /** @description Reconciliation report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        summary: {
                            totalRows: number;
                            parseErrors: number;
                            matched: number;
                            new: number;
                            discrepant: number;
                            dataQualityViolations: number;
                        };
                        parseErrors: {
                            row: number;
                            error: string;
                        }[];
                        dataQualityViolations: {
                            row: number;
                            grantNumber?: string;
                            title: string;
                            piEmail: string;
                            violations: string[];
                        }[];
                        discrepancies: {
                            grantNumber?: string;
                            title: string;
                            piEmail: string;
                            field: string;
                            csvValue: string | number;
                            dbValue: string | number;
                        }[];
                        new: {
                            grantNumber?: string;
                            title: string;
                            piEmail: string;
                            department: string;
                            amount: number;
                            status: string;
                        }[];
                    };
                };
            };
            /** @description Unauthorized — missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden — insufficient role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
